### ISSUE TITLE
Docker container: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mario2130** [SeppPenner/SimpleMqttServer#5]
I am sure that I forgod a litle detail. 

My docker_build is this:
`dotnet publish -c Release --output publish/
docker build --tag=simplemqttserver:1.0.2 .
docker run -d --name="simplemqttserver" -p 1883:1883 -p 8883:8883 --restart=always simplemqttserver:1.0.2`

And my error is this:
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.

   at SimpleMqttServer.Program.Main() in C:\GitHub\SimpleMqttServer\src\SimpleMqttServer\Program.cs:line 58`

It in next code line:
`  var optionsBuilder = new MqttServerOptionsBuilder()`

Any way, thank for you work
ps: sorry my english :D

**Comment by mario2130** [comment]
I found my problem, I changed this line.

` //var filePath = $"{currentPath}\\config.json";`

for this: 
`var filePath = Path.Combine(currentPath, "config.json");`
           


greetting from Chile

**Comment by SeppPenner** [comment]
Hi, I didn't answer yesterday, but I was on the way to completely rework the project. Take a look at the new version (It should work properly on Windows and in Docker) with appsettings.json following the Microsoft standard.
