### ISSUE TITLE
How i can deploye in IIS?

### ISSUE THREAD

**Issue by Rajdipkhavad** [SeppPenner/SimpleMqttServer#7]
If start server by clicking on the.exe file, then it will start work fine, but when i put same in IIS site, then it is not working, I am not sure why, Can you please suggest on this?

**Comment by SeppPenner** [comment]
I'm not an expert here (Never used IIS), but I guess you need e web.config file that starts the service: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-8.0

You can also test within Visual Studio like this: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-8.0
